# --------------------
# Define default values
# --------------------

# ==================== Alas ====================

Alas:
  Emulator:
    ScreenshotMethod: scrcpy

# ==================== Daily ====================

Freebies:
  Scheduler:
    Enable: true
