# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    DataUpdate:
      - Scheduler
      - ItemStorage
    Freebies:
      - Scheduler
      - ShopGift
      - GachaGift
      - Mailbox
    Production:
      - Scheduler
      - ProductionInterval
    Balloon:
      - Scheduler
    Guild:
      - Scheduler
      - GuildCheckIn
      - GuildBattle
      - GuildGacha
    
